PIH/openmrs-config-pihemr

install.sh, watch.sh
See https://github.com/PIH/openmrs-config-zl/pull/9
=> basic utility scripts to run mvn install and watch commands

configuration/pih/htmlforms/labResults.xml
https://pihemr.atlassian.net/browse/UHM-4579
=> UHM-4579 Standalone lab results view on tablet

configuration/pih/htmlforms/mentalHealth.xml
https://pihemr.atlassian.net/browse/UHM-4612
=> Add postSubmissionAction to form with encounterDisposition

configuration/pih/scripts/visit/encounterTypeConfig.js
https://pihemr.atlassian.net/browse/UHM-4608
=> UHM-4608 EncounterTypeConfig should not reference constants library

configuration/pih/htmlforms/labResults.xml
https://pihemr.atlassian.net/browse/UHM-4579
=> Fix background color of labResults form on tablet

configuration/pih/liquibase/sql/create_functions.sql
Functions needed for SL-176, which is a subtask of SL-175, the dispensing report for Sierra Leone
=> Create functions for SL dispensing export

configuration/reports/reportdescriptors/dataexports/sql/covid19encounterexport.sql
Add return visit date for discharged COVID-19 patients for UHM-4721
=> Add return visit date

configuration/messageproperties/messages_en.properties
=> Liberia specific properties added

configuration/pih/liquibase/sql/create_functions.sql
add functions for given,family names and birthdate for UHM -4780
=> add functions for given,family names and birthdate

configuration/pih/petl/jobs/hiv/patient/source.sql
refactor to use common functions to retrieve patient gender, birthdate, name
=> refactor HIV Patient extraction to incorporate best practices

configuration/globalproperties/gp.xml
=> UHM-4769: Circular workflow app for HIV dispensing

configuration/pih/liquibase/sql/create_functions.sql
functions needed for the HIV dispensing ETL (UHM-4824)
=> functions for HIV dispensing ETL

configuration/pih/petl/jobs/hiv/dispensing/job.yml
yml job to run the HIV dispensing ETL
=> job to run dispensing ETL

configuration/pih/petl/jobs/hiv/dispensing/source.sql
the source SQL for the HIV dispensing ETL
=> Sourcing for the dispensing ETL

configuration/pih/liquibase/sql/create_functions.sql
Add function for ED Triage rewrite (UHM-4876)
=> Add function for ED Triage rewrite

configuration/pih/petl/jobs/hiv/patient/target.sql
add zl emr id, dossier_id, hiv emr id
=> add additional identifiers

configuration/pih/htmlforms/ovcFollowup.xml
https://pihemr.atlassian.net/browse/UHM-4985
See also https://github.com/PIH/openmrs-config-pihemr/pull/88
=> UHM-4985 OVC follow up form

configuration/pih/scripts/visit/encounterTypeConfig.js
https://pihemr.atlassian.net/browse/PER-371
=> PER-371: Consult note form - add outpatientConsult config for Peru

configuration/reports/reportdescriptors/dataexports/sql/labOrdersReport.sql
fix how unknown patient function us used - UHM-5032
=> fix how unknown patient function us used

configuration/pih/scripts/visit/encounterTypeConfig.js
https://github.com/PIH/openmrs-config-zl/pull/38
=> Move hiv forms from hiv/zl/ into hiv/

configuration/reports/reportdescriptors/dataexports/sql/labOrdersReport.sql
=> Add provider type

configuration/pih/liquibase/sql/create_functions.sql
Add new function to return provider type
=> Add provider type function

configuration/pih/scripts/visit/encounterTypeConfig.js
fyi @mogoodrich @lnball @brandones
=> liberia specific anc sections

configuration/pih/petl/jobs/labs/all_lab_orders/job.yml, configuration/pih/petl/jobs/labs/all_lab_results/job.yml
=> Changing relative path

configuration/reports/reportdescriptors/dataexports/sql/hivltfu.sql
Create HIV LTFU Tracking export
=> Create HIV LTFU Tracking export

configuration/reports/reportdescriptors/dataexports/hivltfu.yml
=> new HIV LTFU tracking export

configuration/messageproperties/messages_en.properties
add property for new HIV LTFU export
=> add property for new HIV LTFU export

configuration/pih/liquibase/sql/create_functions.sql
Concept_Name function should use preferred name first
=> Concept_Name function should use preferred name first

configuration/pih/liquibase/liquibase.xml
Tested locally, but please review before pushing.  Thanks.
=> UHM-5226 Liquibase changeset for fixing meds without value_drug

configuration/pih/petl/jobs/hiv/viral_load/target.sql
Add encounter location to VL target table
=> Add encounter location to VL target table

configuration/pih/petl/jobs/hiv/viral_load/source.sql
Add encounter location to VL source SQL
=> Add encounter location to VL source SQL

configuration/pih/petl/jobs/hiv/regimens/target.sql
add encounter location to regimen target
=> add encounter location to regimen target

configuration/pih/petl/jobs/hiv/regimens/source.sql
Add encounter location to regimen source
=> Add encounter location to regimen source

configuration/reports/reportdescriptors/dataexports/sql/labOrdersReport.sql
replace slow functions with SQL
=> replace slow functions with SQL

configuration/pih/liquibase/sql/create_functions.sql
Add function to return obs group id of coded answer
=> Add function to return obs group id of coded answer

configuration/reports/reportdescriptors/dataexports/sql/history.sql
rewrite history export (was slow and failing)
=> rewrite history export

configuration/reports/reportdescriptors/dataexports/sql/exams.sql
rewrite exam export (was extremely slow)
=> rewrite exam export

configuration/reports/reportdescriptors/dataexports/sql/feeding.sql
rewrite feeding export (was extremely slow)
=> rewrite feeding export

configuration/reports/reportdescriptors/dataexports/sql/primaryCarePlans.sql
rewrite primary care plan export (was extremely slow)
=> rewrite primary care plan export

configuration/pih/petl/jobs/hiv/ovc/ovc_program/source.sql
@dmdesimone - I did not test this or try to run it, but expect this will work as requested.
=> UHM-5297 - update concept used for hiv status on ovc etl

configuration/pih/htmlforms/comment.xml
https://pihemr.atlassian.net/browse/UHM-5315
=> UHM-5315 Add Clinical Note encounter type and form

configuration/pih/htmlforms/comment.xml
https://pihemr.atlassian.net/browse/UHM-5315
=> UHM-5315: Form should be called 'Comment'

configuration/pih/liquibase/liquibase.xml
For Liberia only so it will ignore the NCD Intake and Followup forms.
=> LIB-140 Updated liquibase for Liberia NCD forms

configuration/pih/scripts/visit/encounterTypeConfig.js
https://pihemr.atlassian.net/browse/UHM-5315
=> Make Comment editable

configuration/pih/scripts/visit/encounterTypeConfig.js
https://pihemr.atlassian.net/browse/UHM-5315
=> Add icon and showOnVisitList to Comment encounter type config (UHM-5315)

configuration/messageproperties/messages_en.properties, configuration/pih/htmlforms/infantDocumentation.xml, configuration/pih/scripts/visit/encounterTypeConfig.js
Sorry, I forgot to add the form on the previous commit.
=> UHM-5376, add HIV Infant documentation form

configuration/attributetypes/attributetypes.csv, configuration/locations/core-locations.csv, configuration/locationtags/locationtags.csv
https://pihemr.atlassian.net/browse/UHM-4354
=> UHM-4354 Move Location, Location Tag, and Lcation Attribute Types installation out of PIH core and into config repos

configuration/messageproperties/messages_en.properties, configuration/pih/scripts/visit/encounterTypeConfig.js
=> med-order variable for enconterType

configuration/messageproperties/messages_en.properties
add delivery export message properties
=> add delivery message properties

configuration/reports/reportdescriptors/dataexports/sql/vitals.sql
Added TB symptom columns separate.
=> 5393 : Update vitals.sql

configuration/reports/reportdescriptors/dataexports/sql/delivery.sql
allow for null start/end dates
=> allow for null start/end dates

configuration/pih/liquibase/sql/create_functions.sql
=> add concept_in_set function

README.md, configuration/messageproperties/messages_en.properties
See https://github.com/PIH/openmrs-module-mirebalais/pull/170
=> Messages for SPA preview

configuration/pih/liquibase/sql/create_functions.sql
=> Add Diagnosis functions

configuration/pih/liquibase/sql/create_functions.sql
change loc_registered function so it works for all countries, not just Haiti
=> adapt loc_registered for all countries

configuration/messageproperties/messages_fr.properties
add echo message property (fr)
=> add echocardiogram message property (fr)

configuration/messageproperties/messages_en.properties
add echo message property (en)
=> add echocardiogram message property (en)

configuration/messageproperties/messages_ht.properties
add echocardiogram haitian name
=> add echocardiogram haitian name

configuration/pih/liquibase/liquibase.xml
https://pihemr.atlassian.net/browse/UHM-5527
=> UHM-5527 Clean up Encounters without visitsin Mexico

configuration/pih/liquibase/sql/create_functions.sql
limit obs_comments to one result
=> limit obs_comments to one result

configuration/reports/reportdescriptors/dataexports/sql/mentalHealthProgram.sql
=> refactor for performance

configuration/reports/reportdescriptors/dataexports/sql/obgynOverview.sql
use latestEncBetweenDates function to speed up latest vitals
=> use latestEncBetweenDates function to speed up latest vitals

configuration/reports/reportdescriptors/dataexports/sql/obgynExam.sql
additional columns for added obgyn exam fields
=> columns for added obgyn exam fields

configuration/pih/htmlforms/covid19Intake.xml, configuration/pih/htmlforms/section-delivery.xml, configuration/pih/htmlforms/section-obgyn-initial.xml, configuration/pih/scripts/global/mch.js
See https://github.com/PIH/openmrs-config-zl/pull/94
=> Add functions for EDD and next button from config-zl, use on some forms

ci/release.sh
See https://github.com/PIH/openmrs-module-pihcore/pull/286
Successful run: https://bamboo.pih-emr.org/browse/MIREBALAIS-CC-1069
=> UHM-5416 cont'd: Release script should update dependencies in pihcore

configuration/pih/htmlforms/covid19Intake.xml
=> Fix Gestational Age / EDD calculation on covid19Intake form

configuration/pih/htmlforms/admissionNote.xml
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/287
=> UHM-5628: Properly handle visit when admission entered retrospectively

configuration/pih/htmlforms/section-delivery.xml, configuration/pih/scripts/global/mch.js
It is slightly less broken than what was there before. It may or may not need to be changed again once https://pihemr.atlassian.net/browse/UHM-5720 is fixed.
=>  Show last calculated EDD and gestational age at delivery time on delivery form; not working because of HFE bug UHM-5720

configuration/pih/htmlforms/section-history.xml
https://pihemr.atlassian.net/browse/UHM-5676
=> Add EDD calculation to NCD History form (UHM-5676)

configuration/relationshiptypes/core.csv, configuration/relationshiptypes/pih.csv, constants.yml
https://pihemr.atlassian.net/browse/UHM-5559
=> UHM-5559 Set up relationship types in Iniz

configuration/pih/scripts/global/expandable.js
This will be used for medication sections and for contacts in ZL, at least.
=> Create generic form expanding function

configuration/pih/scripts/global/checkboxRadio.js, configuration/pih/scripts/global/mch.js, configuration/pih/scripts/global/nextButton.js
https://pihemr.atlassian.net/browse/UHM-5781
The code had been migrated out of the HTMLForm without changing the `&amp;` to an `&`. So whereas HFE parsed the `&amp;` into an `&` and inserted `&` into the URL bar, the script just put `&amp;` directly into the URL bar.
=> UHM-5781 Fix "goToNextSection" functionality 

configuration/encountertypes/encounterTypes.csv, configuration/messageproperties/messages_en.properties, configuration/pih/scripts/visit/encounterTypeConfig.js, constants.yml
https://github.com/PIH/openmrs-module-pihcore/pull/309
https://github.com/PIH/openmrs-module-mirebalais/pull/187
=> Add initial consult encounter type and form for Peru

configuration/pih/scripts/visit/encounterTypeConfig.js, configuration/programs/programs.csv
=> Program hearts

configuration/reports/reportdescriptors/dataexports/sql/allpatientswithids.sql
Rewrite allpatientswithids as it was failing in HUM prod
=> rewrite allpatientswithids

configuration/reports/reportdescriptors/dataexports/sql/obgynOverview.sql
=> add new fields for J9

configuration/pih/liquibase/sql/create_functions.sql
=> new functions for EID ETL

configuration/pih/liquibase/sql/create_functions.sql
new functions for UHM-5954 and a fix for the currentProgramState functions
=> new functions for UHM-5954

configuration/pih/liquibase/sql/create_functions.sql
new functions to fix "Unknown Location" issue
=> new functions to fix "Unknown Location" issue

configuration/pih/htmlforms/labResults.xml
https://pihemr.atlassian.net/browse/UHM-6029
=> UHM-6029 issues with date of test results on Add Past Labs

configuration/reports/reportdescriptors/dataexports/sql/userAndProviders.sql
@dmdesimone - rather than create a new export, this updates the query of an existing export.  All of the same columns are present as in the pre-existing export, they are just renamed to reflect the requirements on the ticket.  I also preserved the "Date created" column that was previously present.
=> UHM-6005 - Export for user role and permission audit

configuration/messageproperties/messages_encountertypes_en.properties, configuration/messageproperties/messages_encountertypes_es.properties, configuration/pih/scripts/visit/encounterTypeConfig.js
https://github.com/PIH/openmrs-module-pihcore/pull/345
https://github.com/PIH/openmrs-config-ces/pull/62
=> New form Ultrasound

configuration/pih/htmlforms/labResults.xml, configuration/pih/liquibase/liquibase.xml
https://pihemr.atlassian.net/browse/UHM-6065
=> UHM-6065 Change concept for date of test reults on Add Past Lab Results pages

configuration/messageproperties/messages_en.properties, configuration/pih/htmlforms/section-obgyn-initial.xml
=> UHM-6099 Add HIV Test Date/Result to ObGyn form

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/socio-econ.xml
=> UHM-6102 Add residency duration question

configuration/pih/liquibase/liquibase.xml
I ran manually on Thomonde with a problem AND tested locally on my SDK (which already had the changeset).
=> UHM-6462 Updated 20210405-restore-value-drug changeset

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_es.properties, configuration/messageproperties/messages_fr.properties, configuration/messageproperties/messages_ht.properties
Add translation label for viral load history section
=> Viral load history label translation

configuration/pih/htmlforms/section-obgyn-initial.xml
Pending HFE PR: https://github.com/openmrs/openmrs-module-htmlformentry/pull/275
=> UHM-6532, get current program workflow status by UUID

configuration/pih/htmlforms/section-oncology-history.xml
@lnball , please check if these changes work for you. Thanks!
=> calculate last bmi

configuration/pih/htmlforms/section-oncology-plan.xml
Added lab orders to oncology form but the orders are not appearing on the htmlform (view or edit).
=> UHM-6986 Added lab orders to oncology form

configuration/frontend/base-config.json
New configuration for substitution questions answered provided by PIH EMR
=> UHM-6839: Set "Reason for Change" when substituting drugs

configuration/frontend/base-config.json
Config update once update for Dispense ESM PR related to UHM-7153 is merged
=> UHM-7153: Add Status Reason for Pause and Close Statuses

configuration/frontend/base-config.json
=> UHM-7144: Prevent the Pharmacy from Over-dispensing orders

configuration/pih/htmlforms/section-delivery.xml
=> HAI-752: Adding the post-natal form to delivery

configuration/pih/htmlforms/section-delivery.xml
Hi @lnball! Wadson's PR had erased these changes, so to correct it I had to make a new PR.
Please review again.
=> Adding the post-natal form to delivery

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties
=> Translations for HAI-855

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties
=> Translations for additional reasons for patient requiring ART

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
=> HAI-884: Add providers (psychologist and doctor)

configuration/pih/htmlforms/mentalHealth.xml
@mogoodrich @dmdesimone @mseaton  have a look in this please
=> change checkboxes into radio buttons and add new concepts

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
=> Add Psychologue required

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
Ticket https://pihemr.atlassian.net/browse/HAI-888
Ticket https://pihemr.atlassian.net/browse/HAI-869
Ticket https://pihemr.atlassian.net/browse/HAI-868
working in 3 tickets in this single branch
@lnball @mogoodrich Please have a look on the PR !
=> working in 3 tickets in this single branch

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
Ticket1: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-886
Ticket2: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-865
Please review this PR
=> working in 2 tickets in this single branch

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
Ticket: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-887
Ticket: https://pihemr.atlassian.net/jira/software/c/projects/HAI/boards/156?selectedIssue=HAI-866
Please review this PR
=> working in tickets(HAI-887 and HAI-866)

configuration/reports/reportdescriptors/dataexports/sql/obgynOverview.sql
=> Update OBGYN visit export

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties
add  (Lost to followup) translation to emr @dmdesimone  Please review it for me
=> add translation to emr

configuration/pih/htmlforms/mentalHealth.xml
=> changed  psychologist and dataclerk  encounterRole

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
@cioan @mseaton  @lnball 
have a look that PR
I have created this branch to work on five tickets because of concerning the same form
=> add new fields on Mental Health form

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
@lnball This branch contains 6 tickets. they are all ready to be reviewed
=> adding new field in the mental health form section

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/mentalHealth.xml
@lnball fixing answer codes translation on Thought content and thought process. Please have a look
=> fixing answer codes translation on Thought content and thought process

configuration/pih/liquibase/liquibase.xml
Retires wart concept and removes its' mappings (PIH:3788 and PIH:WART).
=> UHM-7793 Retire old wart concept

configuration/locationtags/locationtags.csv, configuration/messageproperties/messages_en.properties, configuration/privileges/privileges.csv, constants.yml
Added the privileges and location tags needed to display the new MCOE triage form.
=> SL-553: add location and privilege for MCOE triage form and visit action

configuration/programs/programs.csv
The other configs are coming...
=> LIB-325 Added order to programs

configuration/pih/htmlforms/mentalHealth.xml
adding 'additional comment field to mental health section
@lnball , Please have a look
=> adding 'additional comment field to mental health section'

configuration/encountertypes/encounterTypes.csv, constants.yml
This goes with 2 other PRs: https://pihemr.atlassian.net/browse/UHM-8109
=> UHM_8109 Changed encounter type name physical Rehab

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/section-obgyn-initial.xml
Add weight and Ectopic to OB/GYN Form
=> Add weight and Ectopic field

configuration/pih/htmlforms/drugRehab.xml
@lnball I have finished create the field in this form. please have a look
=> Drug rehabilitation htmlform

configuration/messageproperties/messages_fr.properties
Let me know what you think of the shortened names for the buttons
=> UHM-8190 Updated to shortened French button names

configuration/encountertypes/encounterTypes.csv, configuration/messageproperties/messages_en.properties, configuration/metadatatermmappings/metadataMappings.csv, constants.yml
(add new encounter types for Inpatient Note and Transfer Request with appropriate mappings)
=> SL-767: Fixes to Ward App Configuration

configuration/pih/htmlforms/mentalHealth.xml
I remove the traumatic event check box. 
Please Check it out and merge
=> remove second checkbox

configuration/pih/liquibase/liquibase.xml
@dmdesimone Can you review my changeSet to remove the wrong mapping?
=> UHM-8301 Added checksum for deleting wrong PIH:20208 mapping

configuration/pih/htmlforms/mentalHealth.xml, configuration/pih/scripts/global/mch.js
The last Change  I  made adding addtional concepts Ids @lnball
=> fixing some issue in the Diagnostic Form

configuration/pih/scripts/visit/encounterTypeConfig.js
Created Version 2 forms for NCD intake and followup. This goes with another PR for openmrs-config-liberia for the forms and sections.
Do not merge until after the Liberia release (12/2024) and Tommy's approval.
=> LIB-346 Added the upgraded Liberia NCD forms (V2)

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties, configuration/pih/htmlforms/section-obgyn-initial.xml
add english translation  to 'Type de consultation'
=> add english translation  to 'Type de consultation'

configuration/pih/htmlforms/section-delivery.xml, configuration/pih/scripts/global/mch.js
Make some field in the MHC Accouchement required based on specific selection
=> Make some field in the MHC Accouchement required based on specific selection

configuration/pih/liquibase/liquibase.xml
Can you review the liquibase changeset before I merge it?  @dmdesimone
=> UHM-8407 Migration script for ZL mental health suicide interventions

configuration/pih/htmlforms/section-delivery.xml, configuration/pih/scripts/global/mch.js
@mogoodrich , here is the fix for this function:
=> UHM-8402: fix the calculation of the gestational age

configuration/pih/htmlforms/section-obgyn-plan.xml
Adding the Analysis section to the OBGYN form.
=> HAI-1046: MCH - OBGYN : Ananlysis section added

configuration/frontend/base-config.json
Adding config to hide the left nav in the home app and dispensing app.
=> UHM-8242 hide O3 left nav in home app and dispensing app

configuration/messageproperties/messages_en.properties, configuration/messageproperties/messages_fr.properties
=> HAI-1048: Translation for PMTCT label widget

configuration/pih/htmlforms/mentalHealth.xml
=> HAI-1060: Display entered diagnoses when in view mode

configuration/frontend/base-config.json
This should reduce the number of redirects on idle logout.
=> UHM-8649 redirect O3 idle logout directly to login page

configuration/reports/reportdescriptors/dataexports/sql/all_medication_prescribed.sql
Added new fields for encounter type and prescription observation group ID. Updated temporary medication orders with additional data from observations and orders.
=> UHM-8696 include meds prescribed as obs
